// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eczfacpnbtwiaauzemvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjemZhY3BuYnR3aWFhdXplbXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjc5MjUsImV4cCI6MjA2NTkwMzkyNX0.lPT-zT90GWxI5jSXofOwLFDpJP2CKesOSRyy1o-P_jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);